In [67]:
import random
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [68]:
random.seed(11)
p1 = [random.uniform(-1,1), random.uniform(-1,1)]
p2 = [random.uniform(-1,1), random.uniform(-1,1)]
print(p1,p2)

[-0.09524089298036276, 0.11954477216099191] [0.8484211680474587, -0.06869985980045334]


In [69]:
plt.xlim(-1,1)
plt.ylim(-1,1)
m = (p2[1]-p1[1])/(p2[0]-p1[0])
b = p1[1]-m*p1[0]
x_values = np.linspace(-1,1,100)
y_values = x_values*m + b
plt.plot(x_values,y_values)

In [70]:
x0 = 0
x1values = []
x2values = []
for index in range(10):
    x1 = random.uniform(-1,1)
    x2 = random.uniform(-1,1)
    x1values.append(x1)
    x2values.append(x2)
    
plt.scatter(x1values,x2values, color='red')
plt.show()
    

In [114]:
x0 = [1 for x in range(10)]
x = np.array([x0,x1values,x2values])#, np.float64)

In [115]:
print(y)
print(x)
print(h)

[ 1. -1.  1. -1.  1. -1.  1.  1. -1. -1.]
[[ 1.          1.          1.          1.          1.          1.          1.
   1.          1.          1.        ]
 [ 0.01568255 -0.63067931  0.25976544 -0.81175309 -0.81865893  0.38687697
   0.96438684  0.30784507 -0.68501181  0.05676253]
 [ 0.17476966  0.02381728  0.58595375 -0.39319747  0.61928907 -0.91623933
   0.92951556  0.23112541 -0.96999853 -0.88089779]]
[[ 1. -1.  1. -1.  1. -1.  1.  1. -1. -1.]]


In [119]:
w = np.array([[0],[0],[0]])
#print(w)
y = np.sign(x2values-(np.multiply(x1values,m)+b))

#print(h)
#print(y)
for index in range(1000):
    i = random.randrange(10)
    h= np.sign(np.dot(np.transpose(w),x))
    if h[0,i]!=y[i]:
        w = (w.T + y[i]*(x[:,i])).T
        print(w)
    

signn = np.sign(w[1]*x[:,1]+w[2]*x[:,2])
print(signn)

        
    

    
    

[[ 1.        ]
 [ 0.25976544]
 [ 0.58595375]]
[[ 0.        ]
 [ 0.94477725]
 [ 1.55595227]]
[ 1. -1.  1.]


In [62]:
a = np.array([[1],[1]])
b = np.array([[2],[2]])
print(a+b)

[[3]
 [3]]
